##############################
# Please edit this line to "not_sample_anymore" to make the bot run
is_example_config_or_not: "not_sample_anymore"
##############################
bot_token: "1154912842:AAEjEhqhmlWmb95hFTT-q0BF156Oz2jOLok"
owner_id: 450377297
owner_username: "VivKL"
database_url: "postgres://ifyqrleaqtqdne:3f9df944006cf4f0c9d8c76397eb4adffb1fafca27b70c808bc79ffc33f3ff1d@ec2-54-81-37-115.compute-1.amazonaws.com:5432/d1nh99biq1v8mp"
message_dump: "CHAT ID"
load: []
no_load: []
strict_antispam: False
workers: 4
allow_excl: False
deepfry_token: None
del_cmds: False
sw_api: ''

# Permission
sudo_users: []
support_users: []
whitelist_users: []
